games:
  - name: Elden Ring
    app_id: 1245620
  - name: Cyberpunk 2077
    app_id: 1091500
  - name: Stardew Valley
    app_id: 413150
  - name: Hades
    app_id: 1145360
  - name: Titanfall 2
    app_id: 1237970
  - name: Forza Horizon 5
    app_id: 1551360

reviews_per_game: 2500
language: english
review_type: all
purchase_type: all
filter: recent
sleep_seconds: 0.8
